interface Window {
  __env__: {
    NEXT_PUBLIC_LEMONSQUEEZY_STORE_ID: string;
    NEXT_PUBLIC_LEMONSQUEEZY_MONTHLY_VARIANT_ID: string;
    NEXT_PUBLIC_LEMONSQUEEZY_YEARLY_VARIANT_ID: string;
    NEXT_PUBLIC_APP_URL: string;
    NEXT_PUBLIC_MONTHLY_CHECKOUT_URL: string;
    NEXT_PUBLIC_YEARLY_CHECKOUT_URL: string;
  }
} 